services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=testeyoux'
      - 'POSTGRES_PASSWORD=TesteYouX'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/tmp/psql
volumes:
  postgres: